--liquibase formatted sql

--changeset a.khaustov:1
CREATE TABLE strategy_session_symbol (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_active boolean,
    strategy_session_id BIGINT NOT NULL,
    symbol_id BIGINT NOT NULL
);

--changeset a.khaustov:2
ALTER TABLE strategy_session_symbol
    ADD CONSTRAINT fk_strategy_session_symbol_strategy_session
    FOREIGN KEY (strategy_session_id) REFERENCES strategy_session (id);

--changeset a.khaustov:3
ALTER TABLE strategy_session_symbol
    ADD CONSTRAINT fk_strategy_session_symbol_symbol_id
    FOREIGN KEY (symbol_id) REFERENCES symbol (id);