--liquibase formatted sql

--changeset a.khaustov:create_orders_table comment:Создание таблицы заказов (orders)
CREATE TABLE orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     size NUMERIC(38, 10),
    open_price DOUBLE PRECISION,
    strategy_result_id BIGINT,
    order_status VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
