--liquibase formatted sql

--changeset a.khaustov:create_open_positions_table
CREATE TABLE open_positions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_price DOUBLE PRECISION,
    symbol VARCHAR(255),
    entry_date TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);