--liquibase formatted sql

--changeset a.khaustov:1 comment:Создание таблицы strategy_session
CREATE TABLE strategy_session (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    period BIGINT,
    timeframe VARCHAR(255),
    volume BIGINT,
    leverage BIGINT,
    strategy_type VARCHAR(255),
    order_size_percent DOUBLE PRECISION,
    max_asset_positions_size_percent DOUBLE PRECISION,
    user_id BIGINT NOT NULL,
    exchange VARCHAR(255),
    fast_ema_period INTEGER,
    slow_ema_period INTEGER,
    short_atr_period INTEGER,
    long_atr_period INTEGER,
    entry_range_divisor DOUBLE PRECISION,
    hit_price_percent DOUBLE PRECISION,
    volatility_coefficient DOUBLE PRECISION,
    hoursToRun BIGINT, -- Note: column name matches @Column(name = "hoursToRun") exactly
    status VARCHAR(255),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP

    -- Assuming the User entity maps to a table named 'users' with a primary key 'id' of type BIGINT
    -- CONSTRAINT fk_strategy_session_user FOREIGN KEY (user_id) REFERENCES users (id) -- Uncomment and adjust if needed
);

--changeset a.khaustov:2 comment:Добавление внешнего ключа для user_id в strategy_session
-- Добавляем внешний ключ отдельным changeset для лучшей управляемости миграциями
-- Замените 'users' и 'id' на актуальные имя таблицы и имя колонки первичного ключа для пользователей, если они отличаются
ALTER TABLE strategy_session
    ADD CONSTRAINT fk_strategy_session_user
    FOREIGN KEY (user_id) REFERENCES users (id);