--liquibase formatted sql

--changeset a.khaustov:1

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Соответствует @Id, @GeneratedValue, Long id
    external_id BIGINT  -- Соответствует @Column(name = "external_id"), Long externalId
);